
[build]
  asset_compilation_files = ["app/assets", "app/javascript", "vendor/javascript", "bin/rails", "config", "lib/tasks", "Rakefile", "config.ru"]
  nix_base_revision = "f8f50093e0d21d7680182dd934c1f7a65768d758"
  nix_base_sha256 = "sha256:0wmzyyv2s0rj55mdybfqppf7xdrj39s2m939knmvw07wygmm8dg2"
  nix_include_tools = true

[runtime]
  additional_packages = ["ffmpeg"]
  ruby_version = "3.1.1"
